import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import TopBar from "@/components/TopBar/TopBar";
import { cn } from "@/lib/utils";
import { GlobalStateProvider } from "@/context/ContextProvider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("flex flex-col min-h-screen", inter.className)}>
        <GlobalStateProvider>
          <ThemeProvider
            defaultTheme="dark"
            attribute="class"
            enableSystem
            disableTransitionOnChange
          >
            <TopBar />
            {children}
            <Toaster className="pointer-events-auto" />
          </ThemeProvider>
        </GlobalStateProvider>
      </body>
    </html>
  );
}
